[package]
name = "etcommon-bigint"
version = "0.2.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Big integer (256-bit and 512-bit) implementation for SputnikVM and other Ethereum Classic clients."
repository = "https://github.com/ethereumproject/etcommon"

[lib]
name = "bigint"

[dependencies]
heapsize = "0.4"
byteorder = "1.0"
rand = "0.3.12"
libc = "0.2"
etcommon-rlp = "0.2"
etcommon-hexutil = "0.2"

[features]
x64asm_arithmetic=[]
rust_arithmetic=[]